### ISSUE TITLE
gulp-minify-html is deprecated

### ISSUE THREAD

**Issue by CREEATION** [haydenbleasel/catalyst#175]
https://www.npmjs.com/package/gulp-minify-html

Was searching for the documentation about minifying options, as the minifer removed necessary whitespaces. The underscore (whitespace) here got removed:

```html
<h1>Hallo_<mark><abbr [...]</h1>
```

Set `loose` to `true` to prevent this:

```json
{
  "quotes": true,
  "loose": true
}
```

Or use another :package: :P

**Comment by haydenbleasel** [comment]
Fixed in latest commit.
